apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-backend-api
  annotations:
    kubernetes.io/change-cause: "Initional deployment of the app"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shop-app
  template:
    metadata:
      name: shop
      labels:
        env: prod
        app: shop-app
        app.kubernetes.io/name: shop-app
    spec:
      containers:
        - name: shop-app
          image: numzon/shop-backend-api:v1
          ports:
            - containerPort: 80
              name: http-web-api
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80

---
apiVersion: v1
kind: Service
metadata:
  name: my-lb-service
spec:
  selector:
    app.kubernetes.io/name: shop-app
  ports:
    - name: shop-app
      protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
