apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 8.11.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false


---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-service
spec:
  version: 8.11.2
  http:
    service:
      spec:
        type: LoadBalancer


#h88Dy57Mkb0ay7R1T4q6LDj3